

services:
  db:
    image: postgres:16
    container_name: fylinde_db_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sylvian
      POSTGRES_DB: address_service_db
      PGUSER: postgres
      PGPASSWORD: Sylvian
      PGHOST: /var/run/postgresql
      
     
      SUPERUSER: fylinde_superuser
      SUPERUSER_PASSWORD: SuperSecret
    volumes:
      - fylinde_db-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    env_file:
      - ./.env
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


  rabbitmq:
    image: rabbitmq:3-management
    container_name: fylinde_rabbitmq_1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - fylinde_rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
     
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: fylinde_elasticsearch_1
    environment:
      - discovery.type=single-node
    ports: 
      - "8200:9200"
    networks:
      - ecommerce_network


  auth-service:
    build: ../auth-service
    container_name: fylinde_auth-service_1
    ports:
      - "8000:8000"
    env_file:
      - ../auth-service/.env
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/auth_service_db"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      USER_SERVICE_URL: http://user-service:8001/users
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ../auth-service:/app
      - /etc/localtime:/etc/localtime:ro
      - ../auth-service/app/migrations:/app/app/migrations
      - fylinde_auth_service_data:/app/data  # Persistent storage for auth service data
    networks:
      - ecommerce_network
    cap_add:
      - SYS_TIME


  user-service:
    build: ../user-service
    container_name: fylinde_user-service_1
    ports:
      - "8001:8001"
    env_file:
      - ../user-service/.env
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/user_service_db"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ../user-service:/app
      - /etc/localtime:/etc/localtime:ro
      - ../user-service/app/migrations:/app/app/migrations
      - fylinde_user_service_data:/app/data  # Persistent storage for user service data
    networks:
      - ecommerce_network
    cap_add:
      - SYS_TIME


  product-service:
    build: 
      context: ../product-service
    container_name: fylinde_product-service_1
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/product_service_db"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8003:8003"
    env_file:
      - ../product-service/.env  
    networks:
      - ecommerce_network  
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ../product-service:/app
      - /etc/localtime:/etc/localtime:ro
      - ../product-service/app/migrations:/app/app/migrations
      - fylinde_product_service_data:/app/data  # Persistent storage for product service data
    cap_add:
      - SYS_TIME

  order-service:
    build: 
      context: ../order-service
    container_name: fylinde_order-service_1
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/order_service_db"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8002:8002"
    env_file:
      - ../order-service/.env  
    networks:
      - ecommerce_network  
    depends_on:
      - db   
      - rabbitmq
    volumes:
      - ../order-service:/app
      - /etc/localtime:/etc/localtime:ro
      - ../order-service/app/migrations:/app/app/migrations
      - fylinde_order_service_data:/app/data  # Persistent storage for order service data
    command: ["sh", "start.sh"]
    cap_add:
      - SYS_TIME

  chatbot-service:
    build:
      context: ../chatbot-service
      dockerfile: Dockerfile
    container_name: fylinde_chatbot-service_1  
    ports:
      - "8004:8004"
    depends_on:
      - auth-service
      - user-service
      - order-service
      - product-service  
      - db
      - rabbitmq  
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/  
    networks:
      - ecommerce_network  
    volumes:
      - ../chatbot-service:/app
      - /etc/localtime:/etc/localtime:ro
      - ../chatbot-service/app/migrations:/app/app/migrations
      - fylinde_chatbot_service_data:/app/data  # Persistent storage for chatbot service data
    cap_add:
      - SYS_TIME

  category-service:
    build: 
      context: ../category-service
      dockerfile: Dockerfile
    container_name: fylinde_category-service_1  
    ports:
      - "8005:8005"  
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/category_service_db" 
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on: 
      - db
      - rabbitmq
    volumes:
      - ../category-service:/app 
      - /etc/localtime:/etc/localtime:ro
      - ../category-service/app/migrations:/app/app/migrations
      - fylinde_category_service_data:/app/data  # Persistent storage for category service data
    networks:
      - ecommerce_network   
    cap_add:
      - SYS_TIME   

  recommendation-service:
    build: 
      context: ../recommendation-service
      dockerfile: Dockerfile
    container_name: fylinde_recommendation-service_1  
    ports:
      - "8006:8006"
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/recommendation_service_db" 
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on: 
      - db  
      - rabbitmq
    volumes:
      - ../recommendation-service:/app 
      - /etc/localtime:/etc/localtime:ro 
      - ../recommendation-service/app/migrations:/app/app/migrations
      - fylinde_recommendation_service_data:/app/data  # Persistent storage for recommendation service data
    networks:
      - ecommerce_network 
    cap_add:
      - SYS_TIME  

  marketplace:
    build: 
      context: ../marketplace
      dockerfile: Dockerfile
    container_name: fylinde_marketplace-service_1  
    ports:
      - "3000:3000"
    networks:
      - ecommerce_network  
    volumes:
      - ../marketplace:/app:rw  # Correct the path relative to microservices-orchestration
      - /app/node_modules  # Exclude node_modules from being overridden
    environment:
      - CHOKIDAR_USEPOLLING=true  # For hot-reloading in Docker
 
    command: yarn start    # Use the React dev server to enable live reloading


            

  address-service:
    build: 
      context: ../address-service
      dockerfile: Dockerfile
    container_name: fylinde_address-service_1  
    ports:
      - "8007:8007"
    networks:
      - ecommerce_network
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/address_service_db" 
      HERE_MAPS_API_KEY: "XeyqiLeQdoOHRl8aM6qxkG1vBYy-uYt-5fuyv7lMg7Y"
      RABBITMQ_HOST: fylinde_rabbitmq
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ../address-service:/app  
      - /etc/localtime:/etc/localtime:ro
      - ../address-service/app/migrations:/app/app/migrations
      - fylinde_address_service_data:/app/data  # Persistent storage for address service data
    depends_on:
      - db
      - rabbitmq  
    cap_add:
      - SYS_TIME  

  collaboration-service:
    build: 
      context: ../collaboration-service
      dockerfile: Dockerfile
    container_name: fylinde_collaboration-service_1  
    ports:
      - "8008:8008"
    networks:
      - ecommerce_network
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/collaboration_service_db" 
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ../collaboration-service:/app 
      - /etc/localtime:/etc/localtime:ro 
      - ../collaboration-service/app/migrations:/app/app/migrations
      - fylinde_collaboration_service_data:/app/data  # Persistent storage for collaboration service data
    depends_on:
      - db 
      - rabbitmq
    cap_add:
      - SYS_TIME   

  logistics-service:
    build: 
      context: ../logistics-service
      dockerfile: Dockerfile
    container_name: fylinde_logistics-service_1  
    ports:
      - "8009:8009"
    networks:
      - ecommerce_network
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/logistics_service_db" 
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ../logistics-service:/app  
      - /etc/localtime:/etc/localtime:ro
      - ../logistics-service/app/migrations:/app/app/migrations
      - fylinde_logistics_service_data:/app/data  # Persistent storage for logistics service data
    depends_on:
      - db 
      - rabbitmq       
    cap_add:
      - SYS_TIME



  brand-service: 
    build: 
      context: ../brand-service
      dockerfile: Dockerfile
    container_name: fylinde_brand-service_1  
    ports:
      - "8010:8010"
    networks:
      - ecommerce_network
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/brand_service_db" 
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ../brand-service:/app  
      - /etc/localtime:/etc/localtime:ro
      - ../brand-service/app/migrations:/app/app/migrations
      - fylinde_brand_service_data:/app/data  # Persistent storage for logistics service data
    depends_on:
      - db 
      - rabbitmq       
    cap_add:
      - SYS_TIME

  search-service:
    build: 
      context: ../search-service
      dockerfile: Dockerfile
    container_name: fylinde_search-service_1  
    ports:
      - "8011:8011"
    depends_on:
      - elasticsearch
    networks:
      - ecommerce_network
    volumes:
      - ../search-service:/app  
      - /etc/localtime:/etc/localtime:ro
      - ../search-service/app/migrations:/app/app/migrations
      - fylinde_search_service_data:/app/data  # Persistent storage for logistics service data
  
  vendor-service:
    build:
      context: ../vendor-service
      dockerfile: Dockerfile
    container_name: fylinde_vendor-service_1
    ports:
      - "8012:8012"
    networks:
      - ecommerce_network
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/vendor_service_db"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - /home/fylinde/fylinde/vendor-service:/app
      - /etc/localtime:/etc/localtime:ro
      - /home/fylinde/fylinde/vendor-service/app/migrations:/app/app/migrations
      - fylinde_vendor_service_data:/app/data # Persistent storage for logistics service data
    depends_on:
      - db
      - rabbitmq
    cap_add:
      - SYS_TIME  

  payment-service:
    build:
      context: ../payment-service
      dockerfile: Dockerfile
    container_name: fylinde_payment-service_1
    ports:
      - "8013:8013"
    networks:
      - ecommerce_network
    environment:
      AUTH_SERVICE_URL: "http://auth-service:8000"  # Pointing to auth-service on port 8000
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/payment_service_db"
    volumes:
      - /home/fylinde/fylinde/payment-service:/app
      - /etc/localtime:/etc/localtime:ro
      - /home/fylinde/fylinde/payment-service/app/migrations:/app/app/migrations
      - fylinde_payment_service_data:/app/data # Persistent storage for logistics service data
    depends_on:
      - db
      - rabbitmq
    cap_add:
      - SYS_TIME  


  tryon-service:
    build:
      context: ../tryon-service
      dockerfile: Dockerfile
    container_name: fylinde_tryon-service_1
    ports:
      - "8014:8014"
    networks:
      - ecommerce_network
    environment:
      #AUTH_SERVICE_URL: "http://auth-service:8000"  # Pointing to auth-service on port 8000
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/tryon_service_db"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/    
    volumes:
      - /home/fylinde/fylinde/tryon-service:/app
      - /etc/localtime:/etc/localtime:ro
      - /home/fylinde/fylinde/tryon-service/app/migrations:/app/app/migrations
      - fylinde_tryon_service_data:/app/data # Persistent storage for logistics service data
    depends_on:
      - db
      - rabbitmq
    cap_add:
      - SYS_TIME   

  shop-service:
    build:
      context: ../shop-service
      dockerfile: Dockerfile
    container_name: fylinde_shop-service_1
    ports:
      - "8015:8015"
    networks:
      - ecommerce_network
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:Sylvian@db:5433/shop_service_db"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - /home/fylinde/fylinde/shop-service:/app
      - /etc/localtime:/etc/localtime:ro
      - /home/fylinde/fylinde/shop-service/app/migrations:/app/app/migrations
      - fylinde_shop_service_data:/app/data # Persistent storage for logistics service data
    depends_on:
      - db
      - rabbitmq
    cap_add:
      - SYS_TIME      


networks:
  ecommerce_network:
    driver: bridge

volumes:
  fylinde_db-data:
  fylinde_rabbitmq_data:
  fylinde_auth_service_data:
  fylinde_user_service_data:
  fylinde_product_service_data:
  fylinde_order_service_data:
  fylinde_chatbot_service_data:
  fylinde_category_service_data:
  fylinde_recommendation_service_data:
  fylinde_address_service_data:
  fylinde_collaboration_service_data:
  fylinde_logistics_service_data:
  fylinde_brand_service_data:
  fylinde_search_service_data:
  fylinde_vendor_service_data:
  fylinde_payment_service_data:
  fylinde_tryon_service_data:
  fylinde_shop_service_data:
